ESTATUS_EDITABLES = {"ACTIVA", "COTIZACION", "APROBADA"}

TRANSICIONES_VALIDAS = {
    "COTIZACION": ["COTIZACION", "APROBADA", "CANCELADA"],
    "APROBADA":   ["APROBADA", "ACTIVA", "CANCELADA"],
    "ACTIVA":     ["ACTIVA", "FINALIZADA", "CANCELADA"],
    "RENTADA":    ["RENTADA", "FINALIZADA", "CANCELADA"],
}